-- Planora Smart Study Scheduler Database Schema
-- Based on Class Diagram

-- Users Table
CREATE TABLE User (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Course Table
CREATE TABLE Course (
    CourseID INT PRIMARY KEY AUTO_INCREMENT,
    CourseName VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User_Course Relationship Table (Many-to-Many)
CREATE TABLE User_Course (
    UserID INT NOT NULL,
    CourseID INT NOT NULL,
    enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (UserID, CourseID),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE
);

-- Schedule Table
CREATE TABLE Schedule (
    ScheduleID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    TaskID INT,
    CourseID INT,
    Deadlines VARCHAR(255),
    startDateTime DATETIME NOT NULL,
    endDateTime DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE SET NULL
);

-- Task Table
CREATE TABLE Task (
    TaskID INT PRIMARY KEY AUTO_INCREMENT,
    ScheduleID INT,
    Title VARCHAR(200) NOT NULL,
    Description TEXT,
    TaskDeadlines DATE,
    Priority VARCHAR(20) DEFAULT 'medium',
    TaskStatus VARCHAR(20) DEFAULT 'pending',
    Deadlines VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ScheduleID) REFERENCES Schedule(ScheduleID) ON DELETE SET NULL
);

-- Update Schedule to reference Task (FK added after Task creation)
ALTER TABLE Schedule 
ADD CONSTRAINT fk_schedule_task 
FOREIGN KEY (TaskID) REFERENCES Task(TaskID) ON DELETE SET NULL;

-- Tracker Table (has relationship with User)
CREATE TABLE Tracker (
    TrackerID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    TaskID INT,
    completionRates INT DEFAULT 0,
    TaskStatus VARCHAR(50) DEFAULT 'pending',
    studyHours INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (TaskID) REFERENCES Task(TaskID) ON DELETE SET NULL
);

-- AIRequest Table
CREATE TABLE AIRequest (
    aiRequestID INT PRIMARY KEY AUTO_INCREMENT,
    userID INT NOT NULL,
    promptText TEXT NOT NULL,
    requestTimeStamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    responseData TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES User(UserID) ON DELETE CASCADE
);

-- AIRecommendation Table (references Schedule, generated by AIRequest)
CREATE TABLE AIRecommendation (
    recommendationID INT PRIMARY KEY AUTO_INCREMENT,
    ScheduleID INT NOT NULL,
    recommendationDesc TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ScheduleID) REFERENCES Schedule(ScheduleID) ON DELETE CASCADE
);

-- Indexes for better query performance
CREATE INDEX idx_user_course_user ON User_Course(UserID);
CREATE INDEX idx_user_course_course ON User_Course(CourseID);
CREATE INDEX idx_schedule_user ON Schedule(UserID);
CREATE INDEX idx_schedule_dates ON Schedule(startDateTime, endDateTime);
CREATE INDEX idx_task_schedule ON Task(ScheduleID);
CREATE INDEX idx_task_status ON Task(TaskStatus);
CREATE INDEX idx_tracker_user ON Tracker(UserID);
CREATE INDEX idx_tracker_task ON Tracker(TaskID);
CREATE INDEX idx_ai_request_user ON AIRequest(userID);
CREATE INDEX idx_ai_recommendation_schedule ON AIRecommendation(ScheduleID);

-- Sample data for testing
-- Insert sample users
INSERT INTO User (Name, Email, Password) VALUES 
('Ahmad', 'ahmad@example.com', '$2y$10$example_hash_here'),
('Sarah', 'sarah@example.com', '$2y$10$example_hash_here');

-- Insert sample courses
INSERT INTO Course (CourseName) VALUES 
('Mathematics'),
('Physics'),
('Programming'),
('Literature'),
('History'),
('Chemistry');

-- Enroll users in courses
INSERT INTO User_Course (UserID, CourseID) VALUES 
(1, 1), (1, 2), (1, 3), (1, 4),
(2, 2), (2, 3), (2, 5);

-- Insert sample schedules
INSERT INTO Schedule (UserID, CourseID, Deadlines, startDateTime, endDateTime) VALUES 
(1, 1, '2024-12-20', '2024-12-18 18:00:00', '2024-12-18 20:00:00'),
(1, 2, '2024-12-22', '2024-12-18 20:00:00', '2024-12-18 22:00:00'),
(1, 3, '2024-12-25', '2024-12-19 12:00:00', '2024-12-19 14:00:00');

-- Insert sample tasks
INSERT INTO Task (ScheduleID, Title, Description, TaskDeadlines, Priority, TaskStatus) VALUES 
(1, 'Complete Chapter 4 Problems', 'Solve all exercises in Chapter 4', '2024-12-20', 'high', 'in_progress'),
(2, 'Physics Lab Report', 'Write up experiment results', '2024-12-22', 'high', 'pending'),
(3, 'Coding Assignment', 'Implement sorting algorithms', '2024-12-25', 'medium', 'pending');